### ISSUE TITLE
Slide Deck and Audio File

### ISSUE THREAD

**Issue by lsilen** [numfocus/TownHall#3]
Here is the slide deck and the chat and recording transcripts from today's Town Hall. We're working on an MP4 file that isn't too large to attach. Unfortunately, MPA files aren't supported. Hopefully, we can add that tomorrow. 

It was excellent to see everyone who was able to join the call! We look forward to answering questions from those of you who weren't able to make it as well as the questions we ran out of time to address during the call. Let's keep the conversations going! 

[Google slides link ](https://docs.google.com/presentation/d/11E8WUwE3xTU0rYD3W9KWpiUawd7NnXvkcVvTn8nDMf4/edit?usp=sharing),[NumFOCUS Town Hall - 2024-02-12 .pdf](https://github.com/numfocus/TownHallCommunityFeedback/files/14253897/NumFOCUS.Town.Hall.-.2024-02-12.pdf), 
[nf_townhall_gmt20240212-175300_recording.transcript.pdf](https://github.com/numfocus/TownHallCommunityFeedback/files/14254379/nf_townhall_gmt20240212-175300_recording.transcript.pdf)
[NF_TownHall_GMT20240212-175300_RecordingnewChat.txt](https://github.com/numfocus/TownHallCommunityFeedback/files/14254200/NF_TownHall_GMT20240212-175300_RecordingnewChat.txt),

**Comment by CAM-Gerlach** [comment]
> We're working on an MP4 file that isn't too large to attach.

Even if your org counts as being on a paid GitHub plan instead of free and thus has a 100 MB file size limit for videos, this still implies a maximum average bit rate of less than 150 kb/s, which is far too low to get any kind of usable video quality out of, even with static backgrounds and very aggressive optimization. If you want to include a video, I recommend just uploading to YouTube (unlisted if desired) and embedding it here.

> Unfortunately, MPA files aren't supported. Hopefully, we can add that tomorrow.

If by this you mean just audio in a MP4 container, you _could_ just mux a MP4 with an audio and no video track, or a simple trivially compressed black screen; the 100 MB limit would allow for excellent audio quality at a bitrate of 128 kb/s, though if your org is on not on a paid plan you'd only have a tenth that, a max of less than 15 kb/s, which even for speech is pretty marginal. I'd suggest just going for the YouTube embedding approach instead.

**Comment by tupui** [comment]
Thank you for sharing all that!

> If you want to include a video, I recommend just uploading to YouTube (unlisted if desired)

It would actually be nice if next time the event could hosted on Youtube or any other streaming platform. The streaming quality would be way better and the chat more usable.

**Comment by CAM-Gerlach** [comment]
That might be a good idea, especially since it seemed the intention was to have a NF staff member summarize the questions from chat and ask them, rather than having people ask their questions themselves, so with a few exceptions only the core NF staff members actually participated in the Zoom call itself.

**Comment by ivanov** [comment]
For anyone wishing to watch the recording, it is here: 

Video Link: [NumFOCUS Town Hall Recording](https://numfocus-org.zoom.us/rec/share/LeWTcIRjp8Sg3SPQCy0VH3IyLm67Qqw8LPSNumApl2GBolqPVdy0GEjgWhafg7nN.MdI23PW1JQzBI3MG)
Passcode: NFtownhall2024-12-02

**Comment by ivanov** [comment]
In [this NumFOCUS concerns post](https://pirsquared.org/blog/numfocus-concerns.html) I include feedback from  many people, including a half-dozen former NumFOCUS board members, who have concerns about the direction of NumFOCUS. I hope it provides more context to the rest of our community.
